SELECT * FROM read_csv('https://data.cityofnewyork.us/api/views/erm2-nwe9/rows.csv?accessType=DOWNLOAD', 
                       header=True, 
                       delim=',', 
                       quote='\"', 
                       ignore_errors=True,
                       columns={'Unique Key': 'BIGINT',
                                'Created Date': 'VARCHAR',
                                'Closed Date': 'VARCHAR',
                                'Agency': 'VARCHAR',
                                'Agency Name': 'VARCHAR',
                                'Complaint Type': 'VARCHAR',
                                'Descriptor': 'VARCHAR',
                                'Location Type': 'VARCHAR',
                                'Incident Zip': 'VARCHAR',
                                'Incident Address': 'VARCHAR',
                                'Street Name': 'VARCHAR',
                                'Cross Street 1': 'VARCHAR',
                                'Cross Street 2': 'VARCHAR',
                                'Intersection Street 1': 'VARCHAR',
                                'Intersection Street 2': 'VARCHAR',
                                'Address Type': 'VARCHAR',
                                'City': 'VARCHAR',
                                'Landmark': 'VARCHAR',
                                'Facility Type': 'VARCHAR',
                                'Status': 'VARCHAR',
                                'Due Date': 'VARCHAR',
                                'Resolution Description': 'VARCHAR',
                                'Resolution Action Updated Date': 'VARCHAR',
                                'Community Board': 'VARCHAR',
                                'BBL': 'VARCHAR',
                                'Borough': 'VARCHAR',
                                'X Coordinate (State Plane)': 'VARCHAR',
                                'Y Coordinate (State Plane)': 'VARCHAR',
                                'Open Data Channel Type': 'VARCHAR',
                                'Park Facility Name': 'VARCHAR',
                                'Park Borough': 'VARCHAR',
                                'Vehicle Type': 'VARCHAR',
                                'Taxi Company Borough': 'VARCHAR',
                                'Taxi Pick Up Location': 'VARCHAR',
                                'Bridge Highway Name': 'VARCHAR',
                                'Bridge Highway Direction': 'VARCHAR',
                                'Road Ramp': 'VARCHAR',
                                'Bridge Highway Segment': 'VARCHAR',
                                'Latitude': 'DOUBLE',
                                'Longitude': 'DOUBLE',
                                'Location': 'VARCHAR'}
                    )